### ISSUE TITLE
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value

### ISSUE THREAD

**Issue by dfl** [zhongpei/Comfyui_image2prompt#13]
I'm running on a Mac M3, just installed, it dowloaded the internlm model and now I get this error message:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/dfl/sd/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dfl/sd/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dfl/sd/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dfl/sd/ComfyUI/custom_nodes/Comfyui_image2prompt/image2text.py", line 27, in get_model
    return (InternlmVLModle(device=device,low_memory=low_memory),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dfl/sd/ComfyUI/custom_nodes/Comfyui_image2prompt/internlm_model.py", line 28, in __init__
    self.model_path, self.model, self.tokenizer = self.load_model(device=device, dtype=dtype)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dfl/sd/ComfyUI/custom_nodes/Comfyui_image2prompt/internlm_model.py", line 57, in load_model
    model = model.cpu().float().eval()
            ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
```

Any suggestions please?

**Comment by zhongpei** [comment]
not support on Mac

**Comment by dfl** [comment]
for others looking, this one works for mac https://github.com/gokayfem/ComfyUI_VLM_nodes
