### ISSUE TITLE
ERROR: Package 'deepseek-vl' requires a different Python: 3.11.8 not in '<3.10,>=3.8'

### ISSUE THREAD

**Issue by kakaxixx** [zhongpei/Comfyui_image2prompt#33]
ERROR: Package 'deepseek-vl' requires a different Python: 3.11.8 not in '<3.10,>=3.8'

**Comment by kakaxixx** [comment]
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\install.py", line 54, in check_and_install
    importlib.import_module(import_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepseek_vl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\__init__.py", line 26, in <module>
    check_and_install("git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096",import_name="deepseek_vl")
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\install.py", line 58, in check_and_install
    install_package(package)
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\install.py", line 14, in install_package
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-cache-dir", package])
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['H:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', '--no-cache-dir', 'git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096']' returned non-zero exit status 1.

Cannot import H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt module for custom nodes: Command '['H:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', '--no-cache-dir', 'git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096']' returned non-zero exit status 1.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: segment_anything in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: timm in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.9.16)
Requirement already satisfied: addict in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: yapf in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.40.2)
Requirement already satisfied: torch in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (2.2.1+cu121)
Requirement already satisfied: torchvision in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.17.1+cu121)
Requirement already satisfied: pyyaml in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: huggingface_hub in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.21.3)
Requirement already satisfied: safetensors in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.4.2)
Requirement already satisfied: importlib-metadata>=6.6.0 in h:\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (7.0.2)
