### ISSUE TITLE
Cannot Import Image2Prompt due to 'deepseek_vl' module error

### ISSUE THREAD

**Issue by camoody1** [zhongpei/Comfyui_image2prompt#34]
The module fails import at start-up due to the following error message. Any ideas for how I can resolve this?

```
Installing deepseek_vl...
Collecting git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096
  Cloning https://github.com/deepseek-ai/DeepSeek-VL.git (to revision 86a3096) to c:\users\christopher\appdata\local\temp\pip-req-build-hulyrn49
  Running command git clone --filter=blob:none --quiet https://github.com/deepseek-ai/DeepSeek-VL.git 'C:\Users\Christopher\AppData\Local\Temp\pip-req-build-hulyrn49'
  WARNING: Did not find branch or tag '86a3096', assuming revision or ref.
  Running command git checkout -q 86a3096
  Resolved https://github.com/deepseek-ai/DeepSeek-VL.git to commit 86a3096
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
transformers的当前版本4.37.1满足要求，无需安装4.37.1版本。
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\__init__.py", line 32, in <module>
    from .image2text import Image2Text, LoadImage2TextModel, Image2TextWithTags
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\image2text.py", line 5, in <module>
    from .deepseek_model import DeepseekVLModel
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt\deepseek_model.py", line 11, in <module>
    from deepseek_vl.models import VLChatProcessor, MultiModalityCausalLM
ModuleNotFoundError: No module named 'deepseek_vl'

Cannot import H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt module for custom nodes: No module named 'deepseek_vl'
```

**Comment by zhongpei** [comment]
maybe try  pip install git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096

**Comment by Vodrin** [comment]
This revision doesn't exist

**Comment by camoody1** [comment]
The log says that it can't find a "branch or tag" named '86a3096'. When I look at the git for that code, the '86a3096' isn't a tag or a branch... it's a commit on the 'main' branch. Does that make a difference?

**Comment by camoody1** [comment]
Oh, I'm sorry. I see that the very next line in the log says 'Resolved https://github.com/deepseek-ai/DeepSeek-VL.git to commit 86a3096'. 😄
