### ISSUE TITLE
Don't work for me unfortunatly

### ISSUE THREAD

**Issue by davedaverave** [zhongpei/Comfyui_image2prompt#45]
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/Comfyui_image2prompt/__init__.py", line 1, in <module>
    from .image2text import Image2Text, LoadImage2TextModel
  File "/notebooks/ComfyUI/custom_nodes/Comfyui_image2prompt/image2text.py", line 1, in <module>
    from .moondream_model import MoondreamModel
  File "/notebooks/ComfyUI/custom_nodes/Comfyui_image2prompt/moondream_model.py", line 8, in <module>
    from torchvision.transforms.v2 import (
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/__init__.py", line 3, in <module>
    from . import functional  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/__init__.py", line 3, in <module>
    from ._utils import is_pure_tensor, register_kernel  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/_utils.py", line 5, in <module>
    from torchvision import tv_tensors
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/__init__.py", line 3, in <module>
    from ._bounding_boxes import BoundingBoxes, BoundingBoxFormat
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_bounding_boxes.py", line 9, in <module>
    from ._tv_tensor import TVTensor
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_tv_tensor.py", line 6, in <module>
    from torch._C import DisableTorchFunctionSubclass
ImportError: cannot import name 'DisableTorchFunctionSubclass' from 'torch._C' (/usr/local/lib/python3.9/dist-packages/torch/_C.cpython-39-x86_64-linux-gnu.so)

Cannot import /notebooks/ComfyUI/custom_nodes/Comfyui_image2prompt module for custom nodes: cannot import name

**Comment by zhongpei** [comment]
torchvision  bug, may be reinstall torchvision,  https://github.com/pytorch/vision/issues/7126
