### ISSUE TITLE
comfyUI e6482fb cannot load nodes

### ISSUE THREAD

**Issue by daniellee2015** [zhongpei/Comfyui_image2prompt#54]
comfyUI e6482fb cannot load nodes, i tried all the way install the plugin. git clone and aki install 
![20240402122039](https://github.com/zhongpei/Comfyui_image2prompt/assets/10824753/44bad39b-4556-4c43-ac1c-a9e5b114c64a)
![20240402122146](https://github.com/zhongpei/Comfyui_image2prompt/assets/10824753/787493a2-8e73-4634-baf4-c68bc4596831)
![20240402122255](https://github.com/zhongpei/Comfyui_image2prompt/assets/10824753/10855a00-2016-4844-aa53-b2b7fc09c9f6)

**Comment by daniellee2015** [comment]
tqdm is already installed.
Installing ImageReward...
Looking in indexes: https://mirror.baidu.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://www.modelscope.cn/api/v1/studio/hanamizukiai/resolver/gradio/pypi-index/index.html
Requirement already satisfied: image-reward in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (1.5)
Requirement already satisfied: huggingface-hub>=0.13.4 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (0.21.4)
Requirement already satisfied: timm==0.6.13 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (0.6.13)
Requirement already satisfied: accelerate>=0.16.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (0.28.0)
Requirement already satisfied: datasets>=2.11.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (2.18.0)
Requirement already satisfied: diffusers>=0.16.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (0.27.2)
Requirement already satisfied: transformers>=4.27.4 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (4.39.2)
Requirement already satisfied: fairscale==0.4.13 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from image-reward) (0.4.13)
Requirement already satisfied: torch>=1.8.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from fairscale==0.4.13->image-reward) (2.2.1+cu121)
Requirement already satisfied: numpy>=1.22.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from fairscale==0.4.13->image-reward) (1.26.4)
Requirement already satisfied: pyyaml in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.6.13->image-reward) (6.0.1)
Requirement already satisfied: torchvision in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.6.13->image-reward) (0.17.1+cu121)
Requirement already satisfied: safetensors>=0.3.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from accelerate>=0.16.0->image-reward) (0.4.2)
Requirement already satisfied: packaging>=20.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from accelerate>=0.16.0->image-reward) (24.0)
Requirement already satisfied: psutil in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from accelerate>=0.16.0->image-reward) (5.9.8)
Requirement already satisfied: pyarrow-hotfix in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (0.6)
Requirement already satisfied: pyarrow>=12.0.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (15.0.2)
Requirement already satisfied: pandas in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (2.2.1)
Requirement already satisfied: xxhash in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (3.4.1)
Requirement already satisfied: aiohttp in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (3.9.3)
Requirement already satisfied: filelock in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (3.13.1)
Requirement already satisfied: multiprocess in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (0.70.16)
Requirement already satisfied: fsspec[http]<=2024.2.0,>=2023.1.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (2024.2.0)
Requirement already satisfied: requests>=2.19.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (4.66.2)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from datasets>=2.11.0->image-reward) (0.3.8)
Requirement already satisfied: Pillow in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from diffusers>=0.16.0->image-reward) (10.1.0)
Requirement already satisfied: importlib-metadata in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from diffusers>=0.16.0->image-reward) (7.1.0)
Requirement already satisfied: regex!=2019.12.17 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from diffusers>=0.16.0->image-reward) (2023.12.25)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface-hub>=0.13.4->image-reward) (4.10.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from transformers>=4.27.4->image-reward) (0.15.2)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from aiohttp->datasets>=2.11.0->image-reward) (23.2.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests>=2.19.0->datasets>=2.11.0->image-reward) (1.26.18)
Requirement already satisfied: networkx in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (3.2.1)
Requirement already satisfied: sympy in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (1.12)
Requirement already satisfied: jinja2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch>=1.8.0->fairscale==0.4.13->image-reward) (3.1.3)
Requirement already satisfied: colorama in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from tqdm>=4.62.1->datasets>=2.11.0->image-reward) (0.4.4)
Requirement already satisfied: zipp>=0.5 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from importlib-metadata->diffusers>=0.16.0->image-reward) (3.18.1)
Requirement already satisfied: pytz>=2020.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from pandas->datasets>=2.11.0->image-reward) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from pandas->datasets>=2.11.0->image-reward) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from pandas->datasets>=2.11.0->image-reward) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.11.0->image-reward) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from jinja2->torch>=1.8.0->fairscale==0.4.13->image-reward) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from sympy->torch>=1.8.0->fairscale==0.4.13->image-reward) (1.3.0)
Pillow的当前版本10.1.0满足要求，无需安装10.1.0版本。
huggingface_hub的当前版本0.21.4满足要求，无需安装0.20.1版本。
PyTorch version 2.2.1+cu121 available.
auto-gptq的当前版本0.7.1满足要求，无需安装0.7.1版本。
einops的当前版本0.7.0满足要求，无需安装0.7.0版本。
torchvision is already installed.
accelerate的当前版本0.28.0满足要求，无需安装0.25.0版本。
timm的当前版本0.6.13低于要求的0.9.16，将尝试安装。
Looking in indexes: https://mirror.baidu.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://www.modelscope.cn/api/v1/studio/hanamizukiai/resolver/gradio/pypi-index/index.html
Collecting timm==0.9.16
  Using cached https://mirror.baidu.com/pypi/packages/68/99/2018622d268f6017ddfa5ee71f070bad5d07590374793166baa102849d17/timm-0.9.16-py3-none-any.whl (2.2 MB)
Requirement already satisfied: safetensors in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.9.16) (0.4.2)
Requirement already satisfied: huggingface_hub in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.9.16) (0.21.4)
Requirement already satisfied: torch in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.9.16) (2.2.1+cu121)
Requirement already satisfied: pyyaml in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.9.16) (6.0.1)
Requirement already satisfied: torchvision in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from timm==0.9.16) (0.17.1+cu121)
Requirement already satisfied: requests in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (2.31.0)
Requirement already satisfied: packaging>=20.9 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (24.0)
Requirement already satisfied: fsspec>=2023.5.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (2024.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (4.10.0)
Requirement already satisfied: filelock in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (3.13.1)
Requirement already satisfied: tqdm>=4.42.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from huggingface_hub->timm==0.9.16) (4.66.2)
Requirement already satisfied: networkx in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch->timm==0.9.16) (3.2.1)
Requirement already satisfied: sympy in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch->timm==0.9.16) (1.12)
Requirement already satisfied: jinja2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torch->timm==0.9.16) (3.1.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torchvision->timm==0.9.16) (10.1.0)
Requirement already satisfied: numpy in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from torchvision->timm==0.9.16) (1.26.4)
Requirement already satisfied: colorama in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from tqdm>=4.42.1->huggingface_hub->timm==0.9.16) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from jinja2->torch->timm==0.9.16) (2.1.5)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests->huggingface_hub->timm==0.9.16) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests->huggingface_hub->timm==0.9.16) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests->huggingface_hub->timm==0.9.16) (1.26.18)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from requests->huggingface_hub->timm==0.9.16) (3.3.2)
Requirement already satisfied: mpmath>=0.19 in d:\ai\comfyui-aki-v1.2\python\lib\site-packages (from sympy->torch->timm==0.9.16) (1.3.0)
Installing collected packages: timm
  Attempting uninstall: timm
    Found existing installation: timm 0.6.13
    Uninstalling timm-0.6.13:
      Successfully uninstalled timm-0.6.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
image-reward 1.5 requires timm==0.6.13, but you have timm 0.9.16 which is incompatible.
Successfully installed timm-0.9.16
timm已安装/更新至版本0.9.16。
autoawq的当前版本0.2.3满足要求，无需安装0.2.3版本。
tiktoken is already installed.
attrdict is already installed.
einops的当前版本0.7.0满足要求，无需安装0.7.0版本。
sentencepiece的当前版本0.1.99低于要求的0.2.0，将尝试安装。
Looking in indexes: https://mirror.baidu.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://www.modelscope.cn/api/v1/studio/hanamizukiai/resolver/gradio/pypi-index/index.html
Collecting sentencepiece==0.2.0
  Using cached https://mirror.baidu.com/pypi/packages/85/f4/4ef1a6e0e9dbd8a60780a91df8b7452ada14cfaa0e17b3b8dfa42cecae18/sentencepiece-0.2.0-cp310-cp310-win_amd64.whl (991 kB)
Installing collected packages: sentencepiece
  Attempting uninstall: sentencepiece
    Found existing installation: sentencepiece 0.1.99
    Uninstalling sentencepiece-0.1.99:
      Successfully uninstalled sentencepiece-0.1.99
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
argostranslate 1.9.1 requires sentencepiece==0.1.99, but you have sentencepiece 0.2.0 which is incompatible.
Successfully installed sentencepiece-0.2.0
sentencepiece已安装/更新至版本0.2.0。
Installing deepseek_vl...
Looking in indexes: https://mirror.baidu.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://www.modelscope.cn/api/v1/studio/hanamizukiai/resolver/gradio/pypi-index/index.html
Collecting git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096
  Cloning https://github.com/deepseek-ai/DeepSeek-VL.git (to revision 86a3096) to c:\users\hgd2002\appdata\local\temp\pip-req-build-bmajmk8q
  Running command git clone --filter=blob:none --quiet https://github.com/deepseek-ai/DeepSeek-VL.git 'C:\Users\HGD2002\AppData\Local\Temp\pip-req-build-bmajmk8q'
  fatal: unable to access 'http://github.com/deepseek-ai/DeepSeek-VL.git/': The requested URL returned error: 403
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/deepseek-ai/DeepSeek-VL.git 'C:\Users\HGD2002\AppData\Local\Temp\pip-req-build-bmajmk8q' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/deepseek-ai/DeepSeek-VL.git 'C:\Users\HGD2002\AppData\Local\Temp\pip-req-build-bmajmk8q' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1.2\custom_nodes\Comfyui_image2prompt\src\install.py", line 59, in check_and_install
    importlib.import_module(import_name)
  File "D:\AI\ComfyUI-aki-v1.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepseek_vl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1.2\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-aki-v1.2\custom_nodes\Comfyui_image2prompt\__init__.py", line 34, in <module>
    check_and_install("git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096",import_name="deepseek_vl")
  File "D:\AI\ComfyUI-aki-v1.2\custom_nodes\Comfyui_image2prompt\src\install.py", line 63, in check_and_install
    install_package(package)
  File "D:\AI\ComfyUI-aki-v1.2\custom_nodes\Comfyui_image2prompt\src\install.py", line 15, in install_package
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-cache-dir", package])
  File "D:\AI\ComfyUI-aki-v1.2\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\AI\\ComfyUI-aki-v1.2\\python\\python.exe', '-m', 'pip', 'install', '--no-cache-dir', 'git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096']' returned non-zero exit status 1.

Cannot import D:\AI\ComfyUI-aki-v1.2\custom_nodes\Comfyui_image2prompt module for custom nodes: Command '['D:\\AI\\ComfyUI-aki-v1.2\\python\\python.exe', '-m', 'pip', 'install', '--no-cache-dir', 'git+https://github.com/deepseek-ai/DeepSeek-VL.git@86a3096']' returned non-zero exit status 1.
