### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by burritotrex** [zhongpei/Comfyui_image2prompt#70]
Can't install the plugin. Tried it via ComfyUI Manager and via git clone to the _custom_nodes_ folder.
Using the following Stand-alone / portable version of ComfyUI:

ComfyUI: 2186[46daf0](2024-05-16)
Manager: V2.15

Getting these errors:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
image-reward 1.5 requires timm==0.6.13, but you have timm 0.9.16 which is incompatible.

 Downloading ffmpy-0.3.2.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-cr3522y0\ffmpy_36f39fee98bd4944a1fea8d6711bbc59\setup.py", line 4, in <module>
          from ffmpy import __version__
      ModuleNotFoundError: No module named 'ffmpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.19.1 requires huggingface-hub>=0.21.2, but you have huggingface-hub 0.20.3 which is incompatible.
image-reward 1.5 requires timm==0.6.13, but you have timm 0.9.16 which is incompatible.

Installed ffmpy via ComfyUI manager, errors still comes up.

**Comment by MattRM2** [comment]
Hi,

I have the same problems, so +1 to have a solution ;)
Thx

Matt

**Comment by DarkAlchy** [comment]
I installed it and end up with a size mismatch "RuntimeError: Error(s) in loading state_dict for Moondream:
        size mismatch for vision_encoder.projection.mlp.fc1.weight: copying a param with shape torch.Size([8192, 2304]) from checkpoint, the shape in current model is torch.Size([8192, 1152])."

**Comment by tarun-parishkaar** [comment]
Hi,

I have the same problems, so +2 to have a solution ;)

Thanks

Tarun

> Hi,
> 
> I have the same problems, so +1 to have a solution ;) Thx
> 
> Matt
