### ISSUE TITLE
The corresponding plug-in and model are installed, but an error occurs when using the prompt_compare workflow.

### ISSUE THREAD

**Issue by Nick258654** [zhongpei/Comfyui_image2prompt#74]
When the network can access Hugging Face Hub normally, the following error pops up when running to loader image to text model.
Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui_image2prompt\src\image2text.py", line 56, in get_model
    return (MoondreamModel(device=device,low_memory=low_memory),)
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui_image2prompt\src\moondream_model.py", line 1179, in __init__
    self.model_path, self.vision_encoder, self.text_model = self.load_model(device=device, dtype=dtype)
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui_image2prompt\src\moondream_model.py", line 1194, in load_model
    model_path = snapshot_download("vikhyatk/moondream1", local_dir=local_dir)
  File "H:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "H:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\_snapshot_download.py", line 236, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

**Comment by lg8910** [comment]
me  too
