### ISSUE TITLE
str object has no attribute get

### ISSUE THREAD

**Issue by isshf** [zhongpei/Comfyui_image2prompt#87]
各位大神有没有遇到str object has no attribute get报错的呀？请问是如何解决的呢？谢谢啦

**Comment by dredshep** [comment]
getting the same, can't execute any workflow no matter how small.

![{14B59238-53B5-4EED-823B-02AD74EBE0C3}](https://github.com/user-attachments/assets/986e21b9-b079-4328-b92f-b1da8dc53239)

# ComfyUI Error Report
## Error Details
- **Node Type:** Image2Text
- **Exception Type:** AttributeError
- **Exception Message:** 'str' object has no attribute 'get'
## Stack Trace
```
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 282, in execute
    input_data_all, missing_keys = get_input_data(inputs, class_def, unique_id, caches.outputs, dynprompt, extra_data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 100, in get_input_data
    if is_link(input_data) and (not input_info or not input_info.get("rawLink", False)):
                                                      ^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** .\main.py
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 11984285216
  - **Torch VRAM Total:** 3791650816
  - **Torch VRAM Free:** 9547296

## Logs
```
2024-11-26 17:18:00,239 - root - INFO - Total VRAM 16376 MB, total RAM 32469 MB
2024-11-26 17:18:00,240 - root - INFO - pytorch version: 2.5.1+cu118
2024-11-26 17:18:00,241 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-26 17:18:00,241 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2024-11-26 17:18:01,702 - root - INFO - Using pytorch cross attention
2024-11-26 17:18:05,301 - root - INFO - [Prompt Server] web root: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-11-26 17:18:06,187 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver\nodes.py", line 5, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

2024-11-26 17:18:06,188 - root - WARNING - Cannot import C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver module for custom nodes: No module named 'piexif'
2024-11-26 17:18:25,100 - root - INFO - 
Import times for custom nodes:
2024-11-26 17:18:25,100 - root - INFO -    0.0 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-26 17:18:25,100 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-11-26 17:18:25,100 - root - INFO -    0.0 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
2024-11-26 17:18:25,101 - root - INFO -    0.0 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-26 17:18:25,101 - root - INFO -    0.0 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-26 17:18:25,101 - root - INFO -    1.7 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-moondream
2024-11-26 17:18:25,101 - root - INFO -   17.2 seconds: C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt
2024-11-26 17:18:25,101 - root - INFO - 
2024-11-26 17:18:25,106 - root - INFO - Starting server

2024-11-26 17:18:25,106 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-26 17:18:41,828 - root - INFO - got prompt
2024-11-26 17:20:40,309 - root - ERROR - !!! Exception during processing !!! 'str' object has no attribute 'get'
2024-11-26 17:20:40,329 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 282, in execute
    input_data_all, missing_keys = get_input_data(inputs, class_def, unique_id, caches.outputs, dynprompt, extra_data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 100, in get_input_data
    if is_link(input_data) and (not input_info or not input_info.get("rawLink", False)):
                                                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

2024-11-26 17:20:40,336 - root - INFO - Prompt executed in 118.49 seconds
2024-11-26 17:21:18,161 - root - INFO - got prompt
2024-11-26 17:21:18,214 - root - ERROR - !!! Exception during processing !!! 'str' object has no attribute 'get'
2024-11-26 17:21:18,214 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 282, in execute
    input_data_all, missing_keys = get_input_data(inputs, class_def, unique_id, caches.outputs, dynprompt, extra_data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 100, in get_input_data
    if is_link(input_data) and (not input_info or not input_info.get("rawLink", False)):
                                                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

2024-11-26 17:21:18,215 - root - INFO - Prompt executed in 0.05 seconds
2024-11-26 17:21:27,501 - root - INFO - got prompt
2024-11-26 17:21:32,714 - root - ERROR - !!! Exception during processing !!! 'str' object has no attribute 'get'
2024-11-26 17:21:32,715 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 282, in execute
    input_data_all, missing_keys = get_input_data(inputs, class_def, unique_id, caches.outputs, dynprompt, extra_data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sebas\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 100, in get_input_data
    if is_link(input_data) and (not input_info or not input_info.get("rawLink", False)):
                                                      ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

2024-11-26 17:21:32,716 - root - INFO - Prompt executed in 5.21 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":3,"type":"Image2Text","pos":{"0":600,"1":300},"size":{"0":332.2300109863281,"1":169.85000610351562},"flags":{},"order":2,"mode":0,"inputs":[{"name":"model","type":"IMAGE2TEXT_MODEL","link":1},{"name":"image","type":"IMAGE","link":2}],"outputs":[{"name":"STRING","type":"STRING","links":[3],"slot_index":0,"shape":6}],"properties":{"Node name for S&R":"Image2Text"},"widgets_values":["Describe this photograph.","",false]},{"id":4,"type":"ShowText|pysssss","pos":{"0":1000,"1":300},"size":{"0":395.489990234375,"1":233.3300018310547},"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":3}],"outputs":[{"name":"STRING","type":"STRING","links":[],"slot_index":0,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":["Description:"]},{"id":2,"type":"LoadImage","pos":{"0":200,"1":400},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["example.png","image"]},{"id":1,"type":"LoadImage2TextModel","pos":{"0":200,"1":200},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE2TEXT_MODEL","type":"IMAGE2TEXT_MODEL","links":[1],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"LoadImage2TextModel"},"widgets_values":["moondream1","cuda",false]}],"links":[[1,1,0,3,0,"IMAGE2TEXT_MODEL"],[2,2,0,3,1,"IMAGE"],[3,3,0,4,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.228459735736741,"offset":[109.62291447322723,-13.24215027300584]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by lixiang927047** [comment]
![image](https://github.com/user-attachments/assets/f875963f-1e95-4f58-b74d-29373e80bd9d)
I change here and it works temporarily, perhaps this works for u
